### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by machanic** [BardOfCodes/universal_pytorch#2]
I use pytorch 0.4.0 to run, but it reports error after many iterations. see below

```
Traceback (most recent call last):
  File "find_uap.py", line 76, in <module>
    max_iter_df=max_iter_df,init_batch_size=batch_size)
  File "/home1/machen/universal_pytorch/utils.py", line 261, in universal_perturbation_data_independant
    fooling_rate,model = get_fooling_rate(data_list,batch_size,v,model)
  File "/home1/machen/universal_pytorch/utils.py", line 298, in get_fooling_rate
    est_labels_pert[m:M] = np.argmax(model(dataset_perturbed_var).data.cpu().numpy(), axis=1).flatten()
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torchvision-0.2.1-py3.5.egg/torchvision/models/vgg.py", line 42, in forward
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 479, in __call__
    hook_result = hook(self, input, result)
  File "/home1/machen/universal_pytorch/utils.py", line 315, in get_norm
    main_value[0] += -torch.log((torch.mean(torch.abs(forward_output))))
RuntimeError: CUDA error: out of memory
```

**Comment by machanic** [comment]
`main_value[0] += -torch.log((torch.mean(torch.abs(forward_output))))`   in  universal_pytorch/utils.py", line 315, in get_norm occurs error
